# Starts the database, API, and documentation services
# Define environment variables for DATABASE_PASSWORD and API_PRIVATE_KEY
# when using this.
version: '3'
services:
  database:
    image: mlposey/mutably-db
    restart: always
    environment:
      - POSTGRES_USER=mutably
      - POSTGRES_DB=mutably
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - database-volume:/var/lib/postgresql/data

  api:
    image: mlposey/mutably-api
    restart: always
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=mutably
      - DATABASE_USER=mutably
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - API_PRIVATE_KEY
    ports:
      - 9000:8080

  api-docs:
    image: mlposey/mutably-docs
    restart: always
    ports:
      - 9090:8080

volumes:
  database-volume: